import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{display:'flex', background:'#0000ff', alignItems:'center', justifyContent:'center', minHeight:'80vh'}}>
        <aside style={{display:'flex', alignItems:'center', justifyContent:'center', width:'50%', minHeight:'80vh', background:'#ff0000'}}>
          <Image width={400} height={400} src="https://assets-br.wemystic.com.br/20191113020124/conheca-a-oracao-poderosa-do-agora-850x640.jpg" alt="louvor" />
        </aside>
        <aside style={{display:'flex', alignItems:'center', justifyContent:'center', width:'50%', minHeight:'80vh', background:'#ffff00'}}>
          <h1>Consulta de igrejas e cultos/missas</h1>
        </aside>
      </main>
    </div>
  )
}

export default Home
